### PR TITLE
feat: add unit test syntax

### PR DESCRIPTION
**Pull request by johnyousif**
Hi, this unit test syntax would be very useful for me! Hopefully you agree :-)

Thanks

### CODE REVIEW

**Comment by johnyousif** [comment]
Hi @xabikos did you see this PR? Is it ok?

**Comment by johnyousif** [comment]
hi @xabikos did you see this PR?

Thanks

**Comment by xabikos** [comment]
Hello @johnyousif 

My apologies for the late reply. Thank you for the contribution and the PR you submitted. 

I am not sure if you know there is a [package](https://github.com/xabikos/vscode-jasmine) that contains many snippets dedicated for testing. And I am sure if you search in the market place you can find some similar snippets too.

So I would prefer to keep only pure JavaScript snippets here and not add any test related ones.

Would this be a nice solution for you?

**Comment by johnyousif** [comment]
Ah that's a perfect solution, thanks @xabikos! PR closed.

**Pull request closed without merging**
